/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://kxhijrznpzhxneq4natyt5xfe4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pkikxmtj5jfgvftn7g5j7zus3a",
    "aws_cognito_identity_pool_id": "us-east-1:e15f9fff-344e-46e9-aa82-5ab453d0840f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z9B6Dsd6T",
    "aws_user_pools_web_client_id": "6sd851eana7fn3s15lgbrqs7o0",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
